// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNa7Y_ml9Ebwm44_dMjzssBXWmp__t1kg',
    appId: '1:764491896660:web:48b4eedd3b91acbec71ac1',
    messagingSenderId: '764491896660',
    projectId: 'flutter-chess-58f75',
    authDomain: 'flutter-chess-58f75.firebaseapp.com',
    databaseURL: 'https://flutter-chess-58f75-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-chess-58f75.firebasestorage.app',
    measurementId: 'G-VTJ80ML8N8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGMjCIAhWbiyoki0-TunIo_l3OFlLVH2A',
    appId: '1:764491896660:android:7d3dfc3480590609c71ac1',
    messagingSenderId: '764491896660',
    projectId: 'flutter-chess-58f75',
    databaseURL: 'https://flutter-chess-58f75-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-chess-58f75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb9fLOTovhFC3alf8VaDzNXHMif9Fkhak',
    appId: '1:764491896660:ios:d276f8175514f8bdc71ac1',
    messagingSenderId: '764491896660',
    projectId: 'flutter-chess-58f75',
    databaseURL: 'https://flutter-chess-58f75-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-chess-58f75.firebasestorage.app',
    androidClientId: '764491896660-ms6g1vd83ha5lihsb2gilaoaj8o6eo0f.apps.googleusercontent.com',
    iosClientId: '764491896660-38sc2dt3he05h6f1u2hfvn34ld48m3l2.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineClass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb9fLOTovhFC3alf8VaDzNXHMif9Fkhak',
    appId: '1:764491896660:ios:d276f8175514f8bdc71ac1',
    messagingSenderId: '764491896660',
    projectId: 'flutter-chess-58f75',
    databaseURL: 'https://flutter-chess-58f75-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-chess-58f75.firebasestorage.app',
    androidClientId: '764491896660-ms6g1vd83ha5lihsb2gilaoaj8o6eo0f.apps.googleusercontent.com',
    iosClientId: '764491896660-38sc2dt3he05h6f1u2hfvn34ld48m3l2.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineClass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNa7Y_ml9Ebwm44_dMjzssBXWmp__t1kg',
    appId: '1:764491896660:web:e57ce7e44381c5fcc71ac1',
    messagingSenderId: '764491896660',
    projectId: 'flutter-chess-58f75',
    authDomain: 'flutter-chess-58f75.firebaseapp.com',
    databaseURL: 'https://flutter-chess-58f75-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-chess-58f75.firebasestorage.app',
    measurementId: 'G-LRD5LZ86LD',
  );

}