// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0jsOKMfiJxYSU4VXDXhVSQwAdcIc0kw8',
    appId: '1:12282274098:web:204ac56a1dba70ceeff72b',
    messagingSenderId: '12282274098',
    projectId: 'mess-management-b82d9',
    authDomain: 'mess-management-b82d9.firebaseapp.com',
    storageBucket: 'mess-management-b82d9.firebasestorage.app',
    measurementId: 'G-FS351TH28T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgqmJur5ZGIpO-WdyxEiVIlyps2jzTZ6k',
    appId: '1:12282274098:android:37c13949d97aa721eff72b',
    messagingSenderId: '12282274098',
    projectId: 'mess-management-b82d9',
    storageBucket: 'mess-management-b82d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWILcjyrVszWkqhMuA5V1L5GYaJMuZHEU',
    appId: '1:12282274098:ios:7e3cd32a403c3e45eff72b',
    messagingSenderId: '12282274098',
    projectId: 'mess-management-b82d9',
    storageBucket: 'mess-management-b82d9.firebasestorage.app',
    iosBundleId: 'com.example.notificationCheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWILcjyrVszWkqhMuA5V1L5GYaJMuZHEU',
    appId: '1:12282274098:ios:7e3cd32a403c3e45eff72b',
    messagingSenderId: '12282274098',
    projectId: 'mess-management-b82d9',
    storageBucket: 'mess-management-b82d9.firebasestorage.app',
    iosBundleId: 'com.example.notificationCheck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0jsOKMfiJxYSU4VXDXhVSQwAdcIc0kw8',
    appId: '1:12282274098:web:f3008e3abff23403eff72b',
    messagingSenderId: '12282274098',
    projectId: 'mess-management-b82d9',
    authDomain: 'mess-management-b82d9.firebaseapp.com',
    storageBucket: 'mess-management-b82d9.firebasestorage.app',
    measurementId: 'G-P1X4MEX1QT',
  );
}
